import type { BlogPipelineRow } from "@/lib/airtable/blog-pipeline";

const PROCESSING_MAX_AGE_MS = 2 * 60 * 60 * 1000;

function isRecentTimestamp(iso: string): boolean {
  if (!iso) return false;
  const time = Date.parse(iso);
  if (!Number.isFinite(time)) return false;
  return Date.now() - time < PROCESSING_MAX_AGE_MS;
}

/** Rows still being generated by Make.com / awaiting first draft. */
export function isBlogProcessing(row: BlogPipelineRow): boolean {
  if (row.blogStatus === "Creating") return true;
  if (row.blogStatus === "Ready" && isRecentTimestamp(row.createdTime || row.lastModified)) return true;
  return false;
}

export function hasProcessingBlogs(rows: BlogPipelineRow[]): boolean {
  return rows.some(isBlogProcessing);
}
